function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Regelkreis_ZD"};
	this.sidHashMap["Regelkreis_ZD"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Regelkreis_ZD:151"};
	this.sidHashMap["Regelkreis_ZD:151"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "Regelkreis_ZD:165"};
	this.sidHashMap["Regelkreis_ZD:165"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<S1>/Soll"] = {sid: "Regelkreis_ZD:152"};
	this.sidHashMap["Regelkreis_ZD:152"] = {rtwname: "<S1>/Soll"};
	this.rtwnameHashMap["<S1>/Ist"] = {sid: "Regelkreis_ZD:153"};
	this.sidHashMap["Regelkreis_ZD:153"] = {rtwname: "<S1>/Ist"};
	this.rtwnameHashMap["<S1>/Saturation1"] = {sid: "Regelkreis_ZD:42"};
	this.sidHashMap["Regelkreis_ZD:42"] = {rtwname: "<S1>/Saturation1"};
	this.rtwnameHashMap["<S1>/zPI_AWU1"] = {sid: "Regelkreis_ZD:165"};
	this.sidHashMap["Regelkreis_ZD:165"] = {rtwname: "<S1>/zPI_AWU1"};
	this.rtwnameHashMap["<S1>/StellU"] = {sid: "Regelkreis_ZD:154"};
	this.sidHashMap["Regelkreis_ZD:154"] = {rtwname: "<S1>/StellU"};
	this.rtwnameHashMap["<S1>/StellB"] = {sid: "Regelkreis_ZD:155"};
	this.sidHashMap["Regelkreis_ZD:155"] = {rtwname: "<S1>/StellB"};
	this.rtwnameHashMap["<S2>/Sollwert"] = {sid: "Regelkreis_ZD:165:207"};
	this.sidHashMap["Regelkreis_ZD:165:207"] = {rtwname: "<S2>/Sollwert"};
	this.rtwnameHashMap["<S2>/Istwert"] = {sid: "Regelkreis_ZD:165:208"};
	this.sidHashMap["Regelkreis_ZD:165:208"] = {rtwname: "<S2>/Istwert"};
	this.rtwnameHashMap["<S2>/."] = {sid: "Regelkreis_ZD:165:209"};
	this.sidHashMap["Regelkreis_ZD:165:209"] = {rtwname: "<S2>/."};
	this.rtwnameHashMap["<S2>/0"] = {sid: "Regelkreis_ZD:165:210"};
	this.sidHashMap["Regelkreis_ZD:165:210"] = {rtwname: "<S2>/0"};
	this.rtwnameHashMap["<S2>/Fcn"] = {sid: "Regelkreis_ZD:165:211"};
	this.sidHashMap["Regelkreis_ZD:165:211"] = {rtwname: "<S2>/Fcn"};
	this.rtwnameHashMap["<S2>/I"] = {sid: "Regelkreis_ZD:165:212"};
	this.sidHashMap["Regelkreis_ZD:165:212"] = {rtwname: "<S2>/I"};
	this.rtwnameHashMap["<S2>/P"] = {sid: "Regelkreis_ZD:165:213"};
	this.sidHashMap["Regelkreis_ZD:165:213"] = {rtwname: "<S2>/P"};
	this.rtwnameHashMap["<S2>/Regel- differenz"] = {sid: "Regelkreis_ZD:165:214"};
	this.sidHashMap["Regelkreis_ZD:165:214"] = {rtwname: "<S2>/Regel- differenz"};
	this.rtwnameHashMap["<S2>/Switch"] = {sid: "Regelkreis_ZD:165:215"};
	this.sidHashMap["Regelkreis_ZD:165:215"] = {rtwname: "<S2>/Switch"};
	this.rtwnameHashMap["<S2>/Unit Delay"] = {sid: "Regelkreis_ZD:165:216"};
	this.sidHashMap["Regelkreis_ZD:165:216"] = {rtwname: "<S2>/Unit Delay"};
	this.rtwnameHashMap["<S2>/Stellgroesse"] = {sid: "Regelkreis_ZD:165:217"};
	this.sidHashMap["Regelkreis_ZD:165:217"] = {rtwname: "<S2>/Stellgroesse"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
